---
- name: Create VPC
  amazon.aws.ec2_vpc_net:
    name: AWS-Bastion-VPC
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    tags:
      Project: vpc-bastion-demo
  register: vpc_result

- name: Set VPC ID fact
  ansible.builtin.set_fact:
    vpc_id: "{{ vpc_result.vpc.id }}"

- name: Create public subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ public_subnet_cidr }}"
    region: "{{ aws_region }}"
    az: "{{ az }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    map_public: true
    tags:
      Name: Public Subnet
  register: public_subnet_result

- name: Create private subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ private_subnet_cidr }}"
    region: "{{ aws_region }}"
    az: "{{ az }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    map_public: false
    tags:
      Name: Private Subnet
  register: private_subnet_result

- name: Set Public and Private Subnet ID facts
  ansible.builtin.set_fact:
    public_subnet_id: "{{ public_subnet_result.subnet.id }}"
    private_subnet_id: "{{ private_subnet_result.subnet.id }}"
